# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398ca4868aebfbd919db1104e18d1df53f7adc127d581acc0f7d3869aa05ddad9032a83874277564d67e2ffb85dc8bef47710c2d4d3274b926cdc3b903edc67b

test:
  secret_key_base: 4714421e84b12d1e905ac290d1e556471815f49948dc723d1283aefef71142c5d4d2e5025627abbc4c66d241ad467d2b4b8ff6f2cbe541eaf4647eeeb0515560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
